version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    volumes:
      - ./quorum-website/QuorumWebsite/html:/html:ro
      - ./conf/nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secret:/etc/ssl/quorum:ro
      - ./mime.types:/etc/nginx/mime.types
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    links:
      - php
      - quorum_server
  quorum_server:
    image: andreasstefik/quorum:9.5.9
    container_name: quorum_server
    expose:
      - "1269"
    volumes:
      - ./quorum-website:/quorum-website
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "
        cp /Quorum/Library/Compiled/Run/QuorumStandardLibrary.js ../quorum-website/QuorumWebsite/html/script/QuorumStandardLibrary.js
        && cp /Quorum/Library/Compiled/Run/load.js /quorum-website/QuorumWebsite/html/script/load.js
        && cp /Quorum/Library/Compiled/Run/load.data /quorum-website/QuorumWebsite/html/script/load.data
        && cp /Quorum/Library/Compiled/Run/load.wasm /quorum-website/QuorumWebsite/html/script/load.wasm
        && cd /quorum-website/QuorumWebsite/
        && find SourceCode -type f ! -name "main.quorum" -exec java -Xmx2g -jar /Quorum/Quorum.jar -library /Quorum/Library SourceCode/main.quorum {} +
        && java -Xmx2g -jar Run/Default.jar
        && cd /Quorum
        && java -Xmx2g -jar Quorum.jar -documentLibrary
        && cp Run/Documents/libraries.html /quorum-website/QuorumWebsite/html/libraries.html
        && cp -R Run/Documents/Libraries /quorum-website/QuorumWebsite/html/Libraries
        && java -Xmx2g -jar Quorum.jar -server"
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./conf/php/PHP.Dockerfile
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_NAME
        - MYSQL_PORT
        - MAILGUN_API_ENDPOINT
        - MAILGUN_API_KEY
        - DOMAIN
    volumes:
      - ./quorum-website/QuorumWebsite/html:/html:ro
      - ./downloads:/var/www/downloads:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - quorum_server
      - mysql
  mysql:
    image: mariadb:10.6.3
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
