version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    volumes:
      - ./html:/html
      - ./conf/nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./secret:/etc/ssl/quorum
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    links:
      - php
      - quorum_server
  quorum_server:
    image: andreasstefik/quorum:9.5
    container_name: quorum_server
    expose:
      - "1269"
    command: sh -c "
        /usr/bin/java -Xmx2g -jar Quorum.jar -server"
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./conf/php/PHP.Dockerfile
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_NAME
        - MYSQL_PORT
        - MAILGUN_API_ENDPOINT
        - MAILGUN_API_KEY
        - DOMAIN
    volumes:
      - ./html:/html
    links:
      - quorum_server
      - mysql
  mysql:
    image: mariadb:10.6.3
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
