version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    volumes:
      - ./html:/html
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    links:
      - php
      - quorum_server   
  certbot:
    image: certbot/certbot:v1.18.0
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
  quorum_server:
    image: openjdk:8-jre-alpine
    container_name: quorum_server
    expose:
      - "1269"
    command: sh -c "
        cd Quorum 
        && /usr/bin/java -Xmx2g -jar Quorum.jar -server"
    volumes:
      - ./Quorum:/Quorum
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./conf/php/PHP.Dockerfile
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_NAME
        - MYSQL_PORT
        - DOMAIN
    volumes:
      - ./html:/html
    links:
      - quorum_server
      - mysql
  mysql:
    image: mariadb:10.6.3
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}